import { Rubik } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/navbar'

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata = {
  title: 'Lucas Méné | Développeur web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={rubik.className}>
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
